### ISSUE TITLE
No luck setting it up

### ISSUE THREAD

**Issue by toblum** [doctormord/Responsive_LED_Control#1]
Dear @doctormord,

I had at look at your project, because it looks great and has all the features where I did not find time yet to implement them.
I tried to make it work, but had no success yet. I patched the library, configured the number of LEDs and PIN, flashed it, connected it to wifi, uploaded the files. Everything seems to be OK, but the LEDs stay black. Tried other sketches on the same hardware without problems.
I think it has to do with the configuration of FastLED, but did not find out whats wrong. Did you experience something similar?

Regards
Tobias

**Comment by doctormord** [comment]
Have you tried erasing the ESP first? What version of fastled are you using? I havent had these issues? The initial standard mode is all leds off.
Regards,
Christian 
-------- Ursprüngliche Nachricht --------Von: Tobias Blum <notifications@github.com> Datum: 30.09.17  22:45  (GMT+01:00) An: doctormord/Responsive_LED_Control <Responsive_LED_Control@noreply.github.com> Cc: Christian Weidner <dr.mord@gmx.de>, Mention <mention@noreply.github.com> Betreff: [doctormord/Responsive_LED_Control] No luck setting it up (#1) 
Dear @doctormord,
I had at look at your project, because it looks great and has all the features where I did not find time yet to implement them.

I tried to make it work, but had no success yet. I patched the library, configured the number of LEDs and PIN, flashed it, connected it to wifi, uploaded the files. Everything seems to be OK, but the LEDs stay black. Tried other sketches on the same hardware without problems.

I think it has to do with the configuration of FastLED, but did not find out whats wrong. Did you experience something similar?
Regards

Tobias

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/doctormord/Responsive_LED_Control","title":"doctormord/Responsive_LED_Control","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/doctormord/Responsive_LED_Control"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"No luck setting it up (#1)"}],"action":{"name":"View Issue","url":"https://github.com/doctormord/Responsive_LED_Control/issues/1"}}}

**Comment by toblum** [comment]
I got it working now. It seems it was a problem with PIN numbering on my "LoLin" NodeMCU board. I had to set #define FASTLED_ESP8266_RAW_PIN_ORDER and PIN to D1 and now it works.
I will now play a bit with it. Looks really nice!
